import argparse
import json
import pickle
import socket
from pathlib import Path
from typing import Dict, Optional

import numpy as np

from local_learner import LocalModel


HEADER_BYTES = 8


def load_client_config(config_path: Optional[Path] = None) -> Dict:
    if config_path is None:
        config_path = Path(__file__).with_name("client_config.json")
    config_path = Path(config_path).resolve()
    with open(config_path, "r", encoding="utf-8") as f:
        cfg = json.load(f)
    cfg["_config_path"] = str(config_path)
    cfg["_config_dir"] = str(config_path.parent)
    return cfg


def send_msg(sock: socket.socket, payload: Dict) -> None:
    data = pickle.dumps(payload)
    sock.sendall(len(data).to_bytes(HEADER_BYTES, "big"))
    sock.sendall(data)


def _recv_exact(sock: socket.socket, n_bytes: int) -> bytes:
    chunks = []
    remaining = n_bytes
    while remaining > 0:
        chunk = sock.recv(remaining)
        if not chunk:
            raise ConnectionError("Socket connection closed while receiving data.")
        chunks.append(chunk)
        remaining -= len(chunk)
    return b"".join(chunks)


def recv_msg(sock: socket.socket) -> Dict:
    size = int.from_bytes(_recv_exact(sock, HEADER_BYTES), "big")
    payload = _recv_exact(sock, size)
    obj = pickle.loads(payload)
    if not isinstance(obj, dict):
        raise TypeError(f"Expected dict payload, received {type(obj).__name__}.")
    return obj


def _expect_message_type(msg: Dict, expected: str, context: str) -> None:
    msg_type = msg.get("type")
    if msg_type != expected:
        raise ValueError(f"{context}: expected message type '{expected}', received '{msg_type}'.")


def _matrix(arr_like, expected_shape=None, name: str = "array") -> np.ndarray:
    arr = np.asarray(arr_like, dtype=float)
    if expected_shape is not None and arr.shape != expected_shape:
        raise ValueError(f"{name} has shape {arr.shape}, expected {expected_shape}.")
    return arr


def _to_col_vector(values, size: int, name: str) -> np.ndarray:
    arr = np.asarray(values, dtype=float).reshape(-1)
    if arr.size != size:
        raise ValueError(f"{name} has {arr.size} entries, expected {size}.")
    return arr.reshape(size, 1)


def _normalize_x_dkf(x_dkf_like, p_m: int, training_time: int, name: str) -> np.ndarray:
    x_dkf = np.asarray(x_dkf_like, dtype=float)
    if x_dkf.shape == (p_m, training_time):
        return x_dkf
    if x_dkf.shape == (training_time, p_m):
        return x_dkf.T
    raise ValueError(f"{name} has shape {x_dkf.shape}, expected {(p_m, training_time)}.")


def _build_local_model(cfg: Dict, bootstrap_msg: Dict) -> LocalModel:
    bundle = bootstrap_msg["bundle"]
    metadata = bootstrap_msg["metadata"]

    client_id_cfg = int(cfg["client"]["client_id"])
    client_id_bundle = int(bundle["client_id"])
    if client_id_cfg != client_id_bundle:
        raise ValueError(
            f"Client config id ({client_id_cfg}) does not match bundle id ({client_id_bundle})."
        )

    training_time = int(metadata["training_time"])
    p_m = int(bundle["p_m"])
    d_m = int(bundle["d_m"])

    a = _matrix(bundle["A"], (p_m, p_m), "A")
    c = _matrix(bundle["C"], (d_m, p_m), "C")
    q = _matrix(bundle["Q"], (p_m, p_m), "Q")
    r = _matrix(bundle["R"], (d_m, d_m), "R")
    x0 = _to_col_vector(bundle["x0"], p_m, "x0")
    y = _matrix(bundle["Y"], (d_m, training_time), "Y")

    local_cfg = cfg["local"]
    comp_data = {
        "A": a,
        "B": np.zeros((p_m, p_m)),
        "C": c,
        "Q": q,
        "R": r,
        "P0": q.copy(),
        "x0": x0,
        "Y": y,
        "d_m": d_m,
        "p_m": p_m,
        "eta_l": float(local_cfg["eta_l"]),
        "eta_g": float(local_cfg["eta_g"]),
        "lambda_l": float(local_cfg["lambda_l"]),
    }

    init_cfg = cfg["initialization"]
    theta_rng = np.random.default_rng(int(init_cfg["theta_seed"]))
    theta_0 = theta_rng.normal(
        float(init_cfg["theta_mean"]),
        float(init_cfg["theta_std"]),
        size=(p_m, d_m),
    )

    model = LocalModel(training_time, comp_data, theta_0)

    x_dkf_est = bundle.get("X_dkf_est")
    if x_dkf_est is not None:
        model.X_dkf = _normalize_x_dkf(
            x_dkf_est, p_m=p_m, training_time=training_time, name="X_dkf_est"
        )
    else:
        # If DKF states were not pre-generated by data pipeline, compute once at startup.
        model.run_DKF()

    x_dkf_pred = bundle.get("X_dkf_pred")
    if x_dkf_pred is not None:
        model.X_dkf_pred = _normalize_x_dkf(
            x_dkf_pred, p_m=p_m, training_time=training_time, name="X_dkf_pred"
        )

    model.X_vfl = np.zeros((p_m, training_time))
    model.X_vfl_pred = np.zeros((p_m, training_time))
    return model


def run_client(config_path: Optional[Path] = None) -> None:
    cfg = load_client_config(config_path)

    client_id = int(cfg["client"]["client_id"])
    network_cfg = cfg["network"]
    server_host = str(network_cfg["server_host"])
    server_port = int(network_cfg["server_port"])
    recv_timeout_sec = float(network_cfg.get("recv_timeout_sec", 120))

    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.settimeout(recv_timeout_sec)
        sock.connect((server_host, server_port))
        print(f"client_{client_id}: connected to {server_host}:{server_port}")

        send_msg(
            sock,
            {
                "type": "hello",
                "client_id": client_id,
                "protocol": "granger_socket_v1",
            },
        )

        bootstrap_msg = recv_msg(sock)
        _expect_message_type(bootstrap_msg, "bootstrap", f"client_{client_id} bootstrap")

        bootstrap_client_id = int(bootstrap_msg.get("client_id", -1))
        if bootstrap_client_id != client_id:
            raise ValueError(
                f"Bootstrap message targeted client_{bootstrap_client_id}, "
                f"but this process is client_{client_id}."
            )

        model = _build_local_model(cfg, bootstrap_msg)
        metadata = bootstrap_msg["metadata"]
        training_time = int(metadata["training_time"])
        num_rounds = int(metadata["num_rounds"])
        if num_rounds > training_time:
            raise ValueError(f"num_rounds={num_rounds} exceeds training_time={training_time}.")

        send_msg(sock, {"type": "bootstrap_ack", "client_id": client_id, "status": "ok"})
        print(f"client_{client_id}: bootstrap acknowledged, entering {num_rounds} rounds")

        while True:
            msg = recv_msg(sock)
            msg_type = msg.get("type")

            if msg_type == "gradient":
                round_idx = int(msg.get("round", -1))
                if round_idx < 0 or round_idx >= num_rounds:
                    raise ValueError(
                        f"client_{client_id}: invalid round {round_idx}, valid range [0, {num_rounds - 1}]"
                    )
                grad_x = _to_col_vector(msg.get("grad_x"), model.p_m, "grad_x")

                x_vfl_t = model.VFL_estimate(round_idx)
                x_vfl_pred_t = model.VFL_prediction(round_idx)
                x_dkf_t = model.X_dkf[:, round_idx : round_idx + 1]
                model.GradDescent(grad_x, round_idx)

                send_msg(
                    sock,
                    {
                        "type": "update",
                        "round": round_idx,
                        "client_id": client_id,
                        "x_dkf": x_dkf_t.reshape(-1),
                        "x_vfl": x_vfl_t.reshape(-1),
                        "x_vfl_pred": x_vfl_pred_t.reshape(-1),
                    },
                )
                print(f"client_{client_id}: sent update for round {round_idx + 1}/{num_rounds}")
                continue

            if msg_type == "stop":
                stop_round = int(msg.get("round", num_rounds))
                print(f"client_{client_id}: received stop at round={stop_round}")
                break

            raise ValueError(
                f"client_{client_id}: unsupported message type '{msg_type}' received."
            )


def main() -> None:
    parser = argparse.ArgumentParser(description="Socket client for federated Granger demo.")
    parser.add_argument(
        "--config",
        type=str,
        default=str(Path(__file__).with_name("client_config.json")),
        help="Path to client config JSON.",
    )
    args = parser.parse_args()
    run_client(Path(args.config))


if __name__ == "__main__":
    main()
